# Generated by Django 3.1.1 on 2021-09-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everythingmusic', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2021-09-28'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
