# Generated by Django 3.1.1 on 2021-10-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everythingmusic', '0007_song_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='popular',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='popular',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='song',
            name='popular',
            field=models.BooleanField(default=True),
        ),
    ]
