# Generated by Django 3.1.1 on 2021-10-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everythingmusic', '0008_auto_20211005_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Banner Image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Banner Image2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Banner Image3')),
            ],
        ),
    ]
