# Generated by Django 3.1.1 on 2021-10-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everythingmusic', '0009_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image3',
        ),
    ]
