# Generated by Django 3.1.1 on 2021-10-05 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('everythingmusic', '0010_auto_20211005_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='everythingmusic.album'),
        ),
    ]
