# Generated by Django 3.1.1 on 2021-10-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everythingmusic', '0011_banner_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistsong',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlistsong',
            name='song',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
    ]
