# Generated by Django 3.1.1 on 2021-10-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everythingmusic', '0013_auto_20211010_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='has_album',
            field=models.BooleanField(default=True),
        ),
    ]
