# Generated by Django 3.1.1 on 2021-10-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everythingmusic', '0014_song_has_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='featued_artist',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
