# Generated by Django 3.1.1 on 2021-10-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everythingmusic', '0015_song_featued_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='has_album',
        ),
        migrations.AddField(
            model_name='song',
            name='has_feature',
            field=models.BooleanField(default=False, verbose_name='Tick if this song have a featuring artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='featued_artist',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
