# Generated by Django 3.1.1 on 2021-10-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everythingmusic', '0017_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyric',
            field=models.TextField(null=True),
        ),
    ]
