# Generated by Django 3.1.1 on 2021-10-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everythingmusic', '0018_song_lyric'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(blank=True, default='uploads/default.jpg', null=True, upload_to='uploads/', verbose_name='Artist Image'),
        ),
        migrations.AlterField(
            model_name='song',
            name='featued_artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
