# Generated by Django 3.1.1 on 2021-10-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everythingmusic', '0019_auto_20211018_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='has_feature',
        ),
        migrations.RemoveField(
            model_name='song',
            name='popular',
        ),
    ]
