# Generated by Django 3.1.1 on 2021-10-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everythingmusic', '0020_auto_20211019_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(),
        ),
    ]
