# Generated by Django 3.1.1 on 2021-10-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everythingmusic', '0023_auto_20211020_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Song Image')),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
