# Generated by Django 3.1.1 on 2021-10-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everythingmusic', '0024_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='popular',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='popular',
        ),
    ]
